export const SHOW_NAV = 'SHOW_NAV'
export const HIDE_NAV = 'HIDE_NAV'
export const TOGGLE_NAV = 'TOGGLE_NAV'
export const SET_HEADER = 'SET_HEADER'
export const SET_DEFAULTHEADER = 'SET_DEFAULTHEADER'
